### ISSUE TITLE
Edge Connector data sheet inconsistencies

### ISSUE THREAD

**Issue by whaleygeek** [microbit-foundation/dev-docs#22] opened 2017-01-10 21:52 UTC
(3) Notes 1 and 4 are not consistent.

microbit.org-ticket: 541

**Comment by microbit-mark** [comment] 2018-04-24 15:35
Do we know what isn't consistent here? Not sure what the wording should be @whaleygeek?

**Comment by microbit-mark** [comment] 2018-05-14 14:56
Closing as I can't work out from the ticket what the issue is and i think the issue is too old to return to the user.

**Closed by microbit-mark** 2018-05-14 14:56 UTC
